{
  mode,
  lib,
  pkgs,
  ...
}: {
  config = lib.mkMerge [
    (lib.optionalAttrs (mode == "home-manager") {
      home.packages = with pkgs;
        [
          alejandra
          arandr
          aria2
          argocd
          awscli2
          discord
          docker-compose
          dos2unix
          fd
          feh
          ffmpeg
          gimp
          glab
          gnuplot
          ipcalc
          jetbrains.datagrip
          jetbrains.idea-ultimate
          jdk
          inkscape
          imagemagick
          kubectl
          kubernetes-helm
          kustomize
          nix-index
          nix-zsh-completions
          nixpkgs-fmt
          nixpkgs-review
          nmap
          openldap
          openssl
          parallel
          postgresql
          pwgen
          rancher
          ripgrep
          rtl-sdr
          s3cmd
          slack
          speedtest-cli
          stern
          teams
          tokei
          transmission
          urlview
          vault
          velero
          virt-manager
          wireshark
          xsel
          yq
        ]
        ++ (lib.optionals pkgs.stdenv.isLinux [
          apache-directory-studio
          adoptopenjdk-icedtea-web
          claws-mail
          evince
          ferdium
          gnucash
          libreoffice
          minecraft
          openboard
          pcmanfm
          xfce.ristretto
          signal-desktop
          spotify
          stellarium
          thunderbird
          vlc
          warsow
          wpa_supplicant_gui
          x11vnc
        ]);
    })
  ];
}
